name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update apt-get
      run: sudo apt-get update
    - name: Install libsdl2-dev
      run: sudo apt-get install libsdl2-dev
    - name: Install libsdl2-image-dev
      run: sudo apt-get install libsdl2-image-dev
    - name: make
      run: make
